import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Select, { StylesConfig, components } from 'react-select'
import { CSSProperties } from 'react'
// Good: Custom component declared outside of the Select scope
type MyOptionType = {
  label: string;
  value: string;
};

const options: MyOptionType[] = [
  { value: "chocolate", label: "Chocolate" },
  { value: "strawberry", label: "Strawberry" },
  { value: "vanilla", label: "Vanilla" }
];

const customControlStyles: CSSProperties = {
  color: "white",
  borderColor: "pink"
};

type IsMulti = false;

const selectStyle: StylesConfig<MyOptionType, IsMulti> = {
  control: (provided, state) => {
    // provided has CSSObject type
    // state has ControlProps type

    // return type is CSSObject which means this line will throw error if uncommented
    // return false;

    return {
      ...provided,
      ...customControlStyles
    };
  }
};

const CustomOption = ({ children, ...props }:any) => {
  return (
    <components.Option {...props}>
      {children}
    </components.Option>
  );
};

const Control = ({ children, ...rest }: any) => (
  <components.Control {...rest}>Sort by:{children}</components.Control>
)

const customStyle = {
  control: (css: any) => ({
      ...css,
      width: '220px',
      paddingLeft: '20px',
      color: 'rgba(107, 114, 128, 1)'
  }),
  option: (css: any, { isSelected }: any) => ({
      ...css,
      top: -5,
      backgroundColor: isSelected ? 'rgba(107, 114, 128, 1)' : '',
      '&:hover': {
          backgroundColor: 'rgba(107, 114, 128, 1)',
          color: 'white'
      },
      padding: '5px'
  }),
  menu: (css: any) => ({
      ...css,
      top: 40,
      width: '220px',
      zIndex: 500
  }),
  singleValue: (css: any) => ({
      ...css,
      color: 'rgba(107, 114, 128, 1)'
  })
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Select options={options} components={{ Control }} styles={customStyle} />
        <Select options={options} styles={selectStyle} />

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
